version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/ARACLX/noddy"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = [
    "nodejs",
    "mongo"
  ]
  dialect = "typescript"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "black"
enabled = true