yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
npmPublishRegistry: "https://npm.pkg.github.com"
cacheFolder: ".yarn/cache"

# TODO: We need to configure scopes that will allow us to use database mixin.
npmRegistryServer: https://registry.yarnpkg.com
npmScopes:
  humwrk:
    npmRegistryServer: https://npm.pkg.github.com/humwrk
