yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"
npmPublishRegistry: "https://npm.pkg.github.com"
cacheFolder: ".yarn/cache"
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
