apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: humwrk-services
build:
  artifacts:
    # - image: humwrk/projects
    #   context: services/projects
    #   docker:
    #     dockerfile: docker/Dockerfile
    - image: humwrk/web-gateway
      context: services/web-gateway
      docker:
        dockerfile: docker/dev.Dockerfile
    - image: humwrk/greeter
      context: services/greeter
      docker:
        dockerfile: docker/dev.Dockerfile
deploy:
  kubectl:
    manifests:
      # - services/projects/k8s/pod.yaml
      - services/web-gateway/k8s/pod.yaml
      - services/web-gateway/k8s/svc.yaml
      - services/greeter/k8s/pod.yaml
