apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: humwrk-services
build:
  artifacts:
    - image: humwrk/web-gateway
      context: services/web-gateway
      docker:
        dockerfile: docker/dev.Dockerfile
    - image: humwrk/greeter
      context: services/greeter
      docker:
        dockerfile: docker/dev.Dockerfile
    - image: humwrk/products
      context: services/products
      docker:
        dockerfile: docker/dev.Dockerfile
deploy:
  kubectl:
    manifests:
      # General Configuration File

      - config/common-env.yaml

      # Infrastructure Services

      - infrastructure/mongodb/deploy.yaml
      - infrastructure/mongodb/svc.yaml
      - infrastructure/mongodb/volume.yaml

      - infrastructure/nats/deploy.yaml
      - infrastructure/nats/svc.yaml

      - infrastructure/redis/deploy.yaml
      - infrastructure/redis/svc.yaml

      # Application Services

      - services/web-gateway/k8s/pod.yaml
      - services/web-gateway/k8s/svc.yaml
      - services/greeter/k8s/pod.yaml
      - services/products/k8s/pod.yaml
