apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: humwrk-services
build:
  artifacts:
    - image: humwrk/humwrk
      context: services/humwrk
      docker:
        dockerfile: docker/dev.Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/pod.yaml
      - k8s/svc.yaml
