apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: humwrk-services
build:
  artifacts:
    # - image: humwrk/projects
    #   context: services/projects
    #   docker:
    #     dockerfile: docker/Dockerfile
    - image: humwrk/web-gateway
      context: services/web-gateway
      docker:
        dockerfile: docker/dev.Dockerfile
