version: 2.1

orbs:
 node: circleci/node@4.0.0
 docker: circleci/docker@1.4.0

executors:
 node:
  docker:
   - image: cimg/node:12.18.2

jobs:
 build:
  working_directory: ~/humwrk
  executor: node
  steps:
   - checkout
   - node/install-yarn
   - run: node --version
   - run: yarn --version
   - node/install-packages:
      app-dir: ~/humwrk
      pkg-manager: yarn
   - run: yarn build