apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-gateway
  name: web-gateway
  annotations: null
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: web-gateway
  # Generally, line bellow should be deleted
  # when we'll have implemented Traefik or Nginx.
  type: LoadBalancer
