apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products
  name: products
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: humwrk/products
          env:
            - name: PORT
              value: "80"
          resources:
            requests:
              cpu: 40m
            limits:
              cpu: 70m
      restartPolicy: Always
